var tabStatus={},version,firstRun=!1,firstUpgrade=!1,blackList=[/^https?:\/\/[^\/]*\.taobao\.com\/.*/i,/^https?:\/\/[^\/]*\.alipay\.com\/.*/i],MAX_LOG=400;(function(){$.ajax("manifest.json",{success:function(a){a=JSON.parse(a);version=a.version;trackVersion(version)}})})();
function startListener(){chrome.extension.onConnect.addListener(function(a){a.sender.tab?initPort(a):console.error("Not connect from tab")});chrome.extension.onRequest.addListener(function(a,c,b){if(c.tab)if("Configuration"==a.command){var d=setting.getPageConfig(a.href);b(d);a.top&&(resetTabStatus(c.tab.id),a={href:a.href,clsid:"NULL",urldetect:!0},!d.pageRule&&setting.getFirstMatchedRule(a,setting.defaultRules)&&detectControl(a,c.tab.id,0))}else"GetNotification"==a.command?getNotification(a,c,b):
"DismissNotification"==a.command?(chrome.tabs.sendRequest(c.tab.id,{command:"DismissNotificationPage"}),b({})):"BlockSite"==a.command&&(setting.blocked.push({type:"wild",value:a.site}),setting.update(),b({}));else console.error("Request from non-tab")})}var blocked={};function notifyUser(a,c){var b=tabStatus[c];if(b.notify&&(b.urldetect||b.count>b.actived))console.log("Notify the user on tab ",c),chrome.tabs.sendRequest(c,{command:"NotifyUser",tabid:c},null)}
var greenIcon=chrome.extension.getURL("icon16.png"),grayIcon=chrome.extension.getURL("icon16-gray.png"),errorIcon=chrome.extension.getURL("icon16-error.png"),responseCommands={};function resetTabStatus(a){tabStatus[a]={count:0,actived:0,error:0,urldetect:0,notify:!0,issueId:null,logs:{"0":[]},objs:{"0":[]},frames:1,tracking:!1}}
function initPort(a){var c=a.sender.tab.id;c in tabStatus||resetTabStatus(c);var b=tabStatus[c],d=tabStatus[c].frames++;b.logs[d]=[];b.objs[d]=[];a.onMessage.addListener(function(b){var a=responseCommands[b.command];a?(delete b.command,a(b,c,d)):console.error("Unknown command "+b.command)});a.onDisconnect.addListener(function(){for(var a=0;a<b.objs[d].length;++a)countTabObject(b,b.objs[d][a],-1);showTabStatus(c);b.tracking?0==b.count&&(window.open("log.html?tabid="+c),b.tracking=!1):window.setTimeout(function(){b.logs[d]=
[];b.objs[d]=[]},6E4)})}chrome.tabs.onRemoved.addListener(function(a){tabStatus[a]&&(tabStatus[a].removed=!0,window.setTimeout(function(){delete tabStatus[a]},3E5))});
function countTabObject(a,c,b){for(var d=0;d<blackList.length;++d)if(c.href.match(blackList[d]))return;setting.getFirstMatchedRule(c,setting.blocked)&&(a.notify=!1);if(c.urldetect)a.urldetect+=b;else if(c.actived?(a.actived+=b,0<b&&trackUse(c.rule)):0<b&&trackNotUse(c.href),a.count+=b,c=setting.getMatchedIssue(c))a.error+=b,a.issueId=c.identifier,0<b&&trackIssue(c)}
function showTabStatus(a){if(!tabStatus[a].removed){var c=tabStatus[a],b="",d=greenIcon;!c.count&&!c.urldetect?chrome.pageAction.hide(a):(chrome.pageAction.show(a),c.urldetect?(d=grayIcon,b=$$("status_urldetect")):0!=c.count&&(0!=c.error?(d=errorIcon,b=$$("status_error")):c.count!=c.actived?(d=grayIcon,b=$$("status_disabled")):(d=greenIcon,b=$$("status_ok"))),chrome.pageAction.setIcon({tabId:a,path:d}),chrome.pageAction.setTitle({tabId:a,title:b}),chrome.pageAction.setPopup({tabId:a,popup:"popup.html?tabid="+
a}))}}function detectControl(a,c,b){var d=tabStatus[c];0!=b&&d.objs[0].length&&(countTabObject(d,d.objs[0][0],-1),d.objs[0]=[]);d.objs[b].push(a);countTabObject(d,a,1);showTabStatus(c);notifyUser(a,c)}responseCommands.DetectControl=detectControl;responseCommands.Log=function(a,c,b){c=tabStatus[c].logs[b];c.length<MAX_LOG?c.push(a.message):c.length==MAX_LOG&&c.push("More logs clipped")};
function generateLogFile(a){var c=tabStatus[a];if(!c)return"No log for tab "+a;var b;b="---------- Start of log --------------\n"+("UserAgent: "+navigator.userAgent+"\n");b+="Extension version: "+version+"\n";b+="\n";for(var d=0,e=0;e<c.frames;++e)if(!(0==c.objs[e].length&&0==c.logs[e].length)){d&&(b+="\n\n");++d;b+="------------ Frame "+(e+1)+" ------------------\n";b+="Objects:\n";for(var f=0;f<c.objs[e].length;++f)b+=JSON.stringify(c.objs[e][f])+"\n";b+="\n";b+="Log:\n";for(f=0;f<c.logs[e].length;++f)b+=
c.logs[e][f]+"\n"}b+="\n---------------- End of log ---------------\n";b+=stringHash(b);return 0==d?"No log for tab "+a:b}
function getNotification(a,c,b){var d=c.tab.id;chrome.tabs.get(d,function(a){var c={};c.tabId=a.id;c.site=a.url.replace(/[^:]*:\/\/([^\/]*).*/,"$1");c.sitePattern=a.url.replace(/([^:]*:\/\/[^\/]*).*/,"$1/*");c.message=tabStatus[d].urldetect?$$("status_urldetect"):$$("status_disabled");c.closeMsg=$$("bar_close");c.enableMsg=$$("bar_enable");c.blockMsg=$$("bar_block",c.site);b(c)})};
